---

- name: Ensure Sonarr paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ sonarr_uid }}"
    group: "{{ sonarr_gid }}"
  with_items:
    - "{{ sonarr_base_path }}"
    - "{{ sonarr_config_path }}"
    - "{{ sonarr_data_path }}"

- name: Ensure Sonarr environment variables file created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ sonarr_config_path }}/{{ item }}"
    mode: 0640
    owner: "{{ sonarr_uid }}"
    group: "{{ sonarr_gid }}"
  with_items:
    - "sonarr.conf"

- name: Ensure Sonarr container image is pulled
  community.docker.docker_image:
    name: "{{ sonarr_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ sonarr_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else sonarr_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure Sonarr container network is created
  community.general.docker_network:
    name: "{{ sonarr_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure Sonarr systemd installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/sonarr.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ sonarr_identifier }}.service"
    mode: 0644
