---

- name: Install Sonarr
  tags:
    - setup-all
    - setup-sonarr
    - install-all
    - install-sonarr
  block:
    - name: Run Sonarr validation tasks
      when: sonarr_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Run Sonarr installation tasks
      when: sonarr_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Uninstall Sonarr
  tags:
    - setup-all
    - setup-sonarr
  block:
    - name: Run Sonarr uninstallation tasks
      when: not sonarr_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
