# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 spatterIight
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Sonarr installation tasks
  when: sonarr_enabled | bool
  tags:
    - setup-all
    - setup-sonarr
    - install-all
    - install-sonarr
  block:
    - name: Validate Sonarr configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Sonarr
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Sonarr uninstallation tasks
  when: not sonarr_enabled | bool
  tags:
    - setup-all
    - setup-sonarr
  block:
    - name: Uninstall Sonarr
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
