---
- name: Fail if required Sonarr settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - sonarr_uid
    - sonarr_gid

- name: Validate Sonarr Traefik configuration
  when: sonarr_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Sonarr Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - sonarr_container_labels_traefik_hostname
        - sonarr_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `sonarr_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if sonarr_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          sonarr_container_labels_traefik_path_prefix (`{{ sonarr_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/sonarr`).
      when: "sonarr_container_labels_traefik_path_prefix != '/' and sonarr_container_labels_traefik_path_prefix[-1] == '/'"
