---

- name: Fail if required Sonarr settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] | length == 0"
  with_items:
    - sonarr_identifier
    - sonarr_uid
    - sonarr_gid
    - sonarr_arch

- name: Fail if Sonarr architecture is not supported
  ansible.builtin.fail:
    msg: >
      Your configuration specifies a CPU architecture (`{{ sonarr_arch }}`) which is not currently supported.
      This Sonarr role also does not support self-building yet, so it's not possible to make use of it.
  when: "sonarr_arch not in ['amd64', 'arm64']"
