# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Include roles
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Include roles
      ansible.builtin.include_role:
        name: "{{ role_name }}"
        public: true
      loop:
        - com.devture.ansible.role.playbook_help
        - com.devture.ansible.role.systemd_docker_base
        - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      loop_control:
        loop_var: role_name

- name: Ensure sonarr service is started
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Reload systemd daemon
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Start sonarr.service
      ansible.builtin.systemd_service:
        name: sonarr.service
        state: started
